#!/usr/bin/bash

# Edit this file as needed to identify location of efriends directory.
# Then copy it to /usr/local/bin.

APPDIR=${HOME}/Dropbox/projects
EFDIR=erep-friends/efriends
RUNAPP=${APPDIR}/${EFDIR}/efriends.py

python3 ${RUNAPP}
